Update README.md file
aweber/aw-grid pull request #11
Opened 2017-07-05 18:24 UTC by davegomez

2017-07-06 20:32 UTC, jordangehman requested changes
Hopefully these changes are clear. I rewrote a lot of it to be more straightforward and consistent.

2017-07-06 20:32 UTC, jordangehman commented on README.md
> +AWeber FlexBox Grid is born from AWeber's need to have a responsive and modern grid system to use on its website and web application. This is why we used FlexBox grid as the base for this project but
`AWeber FlexBox Grid is a responsive modern grid system for creating structured layouts in both websites and web applications. Based on flexbox properties, it is a customized version of the infamous [Flexbox Grid](http://flexboxgrid.com/) and uses SCSS as a preprocessor language for to facilitate development and maintenance.`

`If you find the grid useful in your projects, please give us a star and/or contribute :)`

2017-07-06 20:32 UTC, jordangehman commented on README.md
> +We use [Yarn](https://yarnpkg.com/) as a package manager, please install it before start working on the project.
`Install [Yarn](https://yarnpkg.com/) package manager before starting work on the project.`

2017-07-06 20:32 UTC, jordangehman commented on README.md
> +* Install project’s dependencies
`Install the project's dependencies.`

2017-07-06 20:32 UTC, jordangehman commented on README.md
> +* Fork and clone the **AWeber FlexBox Grid** repository
Add a period to the end.

2017-07-06 20:32 UTC, jordangehman commented on README.md
> +We use SASSDoc to build the project’s documentation although this is not a required step prior to publish a PR.
`Use [SASSDoc](http://sassdoc.com/) to build the project’s documentation, but it is not required to open a PR.`

2017-07-06 20:32 UTC, jordangehman commented on README.md
> +Is very important to lint your code changes before creating the PR so the continuous integration service allows to merge the PR.
`Lint your changes before opening a PR. If you don't, the Continuous Integration (CI) service won't allow your PR to be merged.`

2017-07-06 20:32 UTC, jordangehman commented on README.md
> +If you need or want to check the production output files you can use this command:
`Check the production output files, if needed.`

2017-07-06 20:32 UTC, jordangehman commented on README.md
> +* Lint your changes and create a PR for your changes pointing to `develop` branch
`* Lint your changes before opening a PR.`
`* Open a PR comparing your branch with the `develop` branch as the base.`

2017-07-06 20:32 UTC, jordangehman commented on README.md
> +* Create a branch for your changes using [Git Flow](http://nvie.com/posts/a-successful-git-branching-model/)
Add a period to the end.

2017-07-06 20:32 UTC, jordangehman commented on README.md
> +* Make your changes and document them properly using [SASSDoc](http://sassdoc.com/) guidelines
`* Make your changes and document them using the [SASSDoc](http://sassdoc.com/) guidelines.`

2017-07-07 15:28 UTC, davegomez commented
Proposed changes addressed!

2017-07-07 17:46 UTC, jordangehman requested changes
Just one error.

2017-07-07 17:46 UTC, jordangehman commented on README.md
> +* Open a PR comparing your branch with thedevelopbranch as the base.
The word "develop" should be formatted as code. Looks like a copy/paste issue.

2017-07-07 18:00 UTC, davegomez commented on README.md
> +* Open a PR comparing your branch with thedevelopbranch as the base.
Are you accusing me of copy/pasta? 🤔

Fixed!

2017-07-07 18:19 UTC, jordangehman approved these changes

2017-07-07 18:19 UTC, merged